repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        additional_dependencies: &flake8_dependencies
          - flake8-bugbear==22.7.1
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --profile=black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
  - repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies: *flake8_dependencies
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.7
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-duplicate-keys
          - --remove-all-unused-imports
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
